### ISSUE TITLE
A working purge script.

### ISSUE THREAD

**Issue by Puppercino** [Disconnect24/Mail-Go#5]
We need a mail purge script that can be ran in a crontab/cronjob.
~~~~sql
DELETE FROM WC24Mail.mails WHERE `timestamp` < NOW() - INTERVAL 28 DAY;
~~~~

So far, purge.go _should_ work but can only be ran once every startup or every time it is invoked.
We should work towards making a compatible script that runs every week, etc.

**Comment by Puppercino** [comment]
I committed a possible solution and I'll quickly test it soon.

**Comment by Puppercino** [comment]
Can confirm,
**Solution did not work.**

**Comment by Puppercino** [comment]
Another possible solution has been found, let's find out if it works or not. uwu

**Comment by spotlightishere** [comment]
With love from 04f8eff26f54737ca4f062aba1e44a548ff4a24e - merged into master soon. Once that's done with, we'll tag v1.3.

**Comment by spotlightishere** [comment]
Seems to be working. v1.3 will be held off until it's guaranteed stable everywhere.
